modules:
- postgres:
    tag_version: 0.10.10
    push: false
    build_args:
    - PROTOCOL: postgres
- elasticsearch:
    tag_version: 1.0.4
    push: false
    build_args:
    - PROTOCOL: elasticsearch
- s3:
   tag_version: 0.6.0
   push: false
   build_args:
   - PROTOCOL: s3
